### ISSUE TITLE
Many translations are blank. Search for ":;" to see all blank translations

### ISSUE THREAD

**Issue by BSBMteam** [Gowee/zhconv-rs#2]
Please translate and update this entry! Translation (Counter-Strike) is blank: ”VULCANUS-9 Vulcanus Parts System: Gas line“
```
    {
      "original": "VULCANUS-9 Vulcanus Parts System: Gas line",
      "conv": "zh-hans:;zh-hant:"
    },
```

There are many other instances of a region's translation being blank:
```
    {
      "original": "Speed boost",
      "conv": "zh-hans:;zh-hant:戰鬥靴"
    },
```
As you can see, some regions have no value written under it.  So, you could probably remove those blank region translations
```
    {
      "original": "El otoño del patriarca",
      "conv": "zh-cn:家长的没落;zh-tw:獨裁者的秋天;zh-hk:;zh-sg:;zh-mo:;"
    },
```

**Comment by Gowee** [comment]
Hi! Thanks for the feedback.

All the conversion files under `data/cgroups/` are extracted from Wikipedia. For example, the original file for "Counter-Strike" as indicated by https://github.com/Gowee/zhconv-rs/blob/7be825e8f68b2cc373dcae4a41caf80f06228432/data/cgroups/Counter-Strike.json#L4 is at https://zh.wikipedia.org/wiki/Module:CGroup/Counter-Strike (editable). They are maintained by editors on demand for Wikipedia articles. Hence it is predictable to be non-exhaustive and incomplete. 

These files are meant to be synchronized automatically from the upstream automatically with [the script](https://github.com/Gowee/zhconv-rs/blob/83e3d376010ecaae254c3060ecf2447323aaf0ad/data/cgroup_extractor.py). 

For now, this project has no plan to maintain conversion rules on its own since it would take much much more effort. So any updates are expected to be performed on the upstream (sometimes it is inapplicable, though). The primary goal of the project is to provide an alternative efficient implementation of the converter, other than conversion rules. I will update the README to mention that. I am planning to merge more rules from other existing & well-maintained rulesets such as open-cc to improve the conversion accuracy.

**Comment by Gowee** [comment]
Should be fixed by https://github.com/Gowee/zhconv-rs/commit/83eb76329586fa4b03ef17c571ebb06613406391 https://github.com/Gowee/zhconv-rs/commit/7e50eadbbea3ad4992d61aeb68172d0a96f0727d . Closing for now.
