### ISSUE TITLE
Add missing 麵食 related conversion pairs

### ISSUE THREAD

**Issue by andrewchen5678** [Gowee/zhconv-rs#6]
when I was testing and trying to convert to Chinese Traditional (zh-hant) variant with zhconv-rs 0.3.1 python version, I noticed that 面 is not replaced by 麵 or 麪 for some 麵食 related words:
so far I noticed these ones: 揉面 should be 揉麵 and 和面 should be 和麵, there could me more that I missed.

However, when I try on the https://zhconv.pages.dev/, it does get converted to 麪

**Comment by Gowee** [comment]
Thanks for your feedback.

The project does not maintain any rulesets. They are actually imported and updated regularly from upstream projects.

"揉面"-related pairs are included in OpenCC rulesets:  
https://github.com/Gowee/zhconv-rs/blob/67723c70135d69c1648480a83e158e583cfdc146/data/STPhrases.txt#L26136
, while they are not part of [MediaWiki rulesets](https://github.com/wikimedia/mediawiki/blob/master/includes/languages/data/ZhConversion.php#L14).

We take MediaWiki rulesets, which are maintained by [the Chinese Wikipedia community](https://zh.wikipedia.org/wiki/Wikipedia:%E5%AD%97%E8%AF%8D%E8%BD%AC%E6%8D%A2/%E4%BF%AE%E5%A4%8D%E8%AF%B7%E6%B1%82), as the basic. OpenCC is an optional feature, which is currently only activated in the web app. When activated, OpenCC rulesets are merged into the basic MediaWiki rulesets, which are then compiled into pre-built automaton together.

And sadly, the Python library doesn't ship with OpenCC rulesets for now since the choice of rulesets are determined at compile-time. I am not sure how to make that also optional in a proper way.

**Comment by Gowee** [comment]
Now we have an additional package with OpenCC dicts bulit-in. The issue should be resolved.

Please try with `pip install zhconv-rs-opencc`.
